id: A1BB22C3A
title: Sādhana of Bhaiṣajya Guru (Medicine Buddha)
type: translation
pechas:
- I5F355047
- I6CD62685
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:46:18.858334
  last_modified_at: 2023-01-04 12:46:18.858356
  collections:
  - Karma Chakme Series
  - Works of Tibetan Masters
alignment_to_base:
  I5F355047/E887: DD79
  I6CD62685/877A: DD79
